"""Build and execute SV example notebooks for F6.2."""

from __future__ import annotations

import os
import sys
import nbformat as nbf
from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell

# ============================================================================
# Notebook 1: SV Basic
# ============================================================================

def build_nb1() -> nbf.NotebookNode:
    """01_sv_basic.ipynb — Basic SV model on S&P 500 returns."""
    nb = new_notebook()
    nb.metadata.kernelspec = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }

    # --- Cell 1: Title ---
    nb.cells.append(new_markdown_cell(
        "# Stochastic Volatility — Basic Model\n"
        "\n"
        "This notebook demonstrates the complete stochastic volatility pipeline:\n"
        "\n"
        "1. **Exploratory analysis** of financial returns\n"
        "2. **Particle filtering** of the latent log-volatility $h_t$\n"
        "3. **Parameter estimation** via Particle Marginal Metropolis–Hastings (PMMH)\n"
        "4. **Volatility forecasting** $h$-steps ahead\n"
        "\n"
        "The model is:\n"
        "$$y_t = \\exp(h_t/2)\\,\\varepsilon_t, \\qquad "
        "h_{t+1} = \\mu + \\phi\\,(h_t - \\mu) + \\sigma\\,\\eta_t$$\n"
        "where $\\varepsilon_t, \\eta_t \\sim N(0,1)$ independently."
    ))

    # --- Cell 2: Imports ---
    nb.cells.append(new_code_cell(
        "import sys, os\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "%matplotlib inline\n"
        "from scipy import stats\n"
        "from dataclasses import dataclass\n"
        "import time\n"
        "\n"
        "# Add project root to path\n"
        "sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..', '..', '..')))\n"
        "\n"
        "from particlefilterbox.models.stochastic_volatility import StochasticVolatility\n"
        "from particlefilterbox.pmcmc import PMMH\n"
        "\n"
        "plt.rcParams['figure.figsize'] = (12, 5)\n"
        "plt.rcParams['figure.dpi'] = 100\n"
        "np.random.seed(42)"
    ))

    # --- Cell 3: Load data ---
    nb.cells.append(new_markdown_cell(
        "## 1. Data Loading\n"
        "\n"
        "We use synthetic daily S&P 500 returns calibrated to realistic volatility levels."
    ))
    nb.cells.append(new_code_cell(
        "data_path = os.path.join('..', 'data', 'sp500_returns.csv')\n"
        "df = pd.read_csv(data_path)\n"
        "print(f'Loaded {len(df)} observations')\n"
        "print(df.head())\n"
        "\n"
        "# Use first 500 observations for speed\n"
        "T_use = 500\n"
        "returns = df['returns'].values[:T_use]\n"
        "dates = pd.to_datetime(df['date'].values[:T_use])\n"
        "print(f'Using first {T_use} observations')"
    ))

    # --- Cell 4: Exploratory analysis ---
    nb.cells.append(new_markdown_cell(
        "## 2. Exploratory Analysis\n"
        "\n"
        "Financial returns exhibit **volatility clustering**: large moves tend to follow large moves. "
        "The ACF of squared returns captures this persistence."
    ))
    nb.cells.append(new_code_cell(
        "fig, axes = plt.subplots(2, 2, figsize=(14, 8))\n"
        "\n"
        "# Returns time series\n"
        "axes[0, 0].plot(dates, returns, linewidth=0.5, color='steelblue')\n"
        "axes[0, 0].set_title('Daily Returns')\n"
        "axes[0, 0].set_ylabel('Return')\n"
        "axes[0, 0].axhline(0, color='k', linewidth=0.5)\n"
        "\n"
        "# Histogram\n"
        "axes[0, 1].hist(returns, bins=50, density=True, alpha=0.7, color='steelblue')\n"
        "x_grid = np.linspace(returns.min(), returns.max(), 200)\n"
        "axes[0, 1].plot(x_grid, stats.norm.pdf(x_grid, returns.mean(), returns.std()),\n"
        "               'r-', linewidth=2, label='Normal fit')\n"
        "axes[0, 1].set_title('Return Distribution')\n"
        "axes[0, 1].legend()\n"
        "\n"
        "# ACF of returns\n"
        "max_lag = 40\n"
        "acf_returns = np.array([\n"
        "    np.corrcoef(returns[:-lag], returns[lag:])[0, 1] if lag > 0 else 1.0\n"
        "    for lag in range(max_lag + 1)\n"
        "])\n"
        "axes[1, 0].bar(range(max_lag + 1), acf_returns, color='steelblue', width=0.6)\n"
        "axes[1, 0].axhline(1.96 / np.sqrt(len(returns)), color='r', linestyle='--')\n"
        "axes[1, 0].axhline(-1.96 / np.sqrt(len(returns)), color='r', linestyle='--')\n"
        "axes[1, 0].set_title('ACF of Returns')\n"
        "axes[1, 0].set_xlabel('Lag')\n"
        "\n"
        "# ACF of squared returns\n"
        "sq_returns = returns ** 2\n"
        "acf_sq = np.array([\n"
        "    np.corrcoef(sq_returns[:-lag], sq_returns[lag:])[0, 1] if lag > 0 else 1.0\n"
        "    for lag in range(max_lag + 1)\n"
        "])\n"
        "axes[1, 1].bar(range(max_lag + 1), acf_sq, color='darkorange', width=0.6)\n"
        "axes[1, 1].axhline(1.96 / np.sqrt(len(returns)), color='r', linestyle='--')\n"
        "axes[1, 1].axhline(-1.96 / np.sqrt(len(returns)), color='r', linestyle='--')\n"
        "axes[1, 1].set_title('ACF of Squared Returns (volatility clustering)')\n"
        "axes[1, 1].set_xlabel('Lag')\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print(f'Kurtosis: {stats.kurtosis(returns, fisher=True):.2f} (excess, normal=0)')\n"
        "print(f'Skewness: {stats.skew(returns):.3f}')\n"
        "print(f'Mean: {returns.mean():.6f}, Std: {returns.std():.6f}')"
    ))

    # --- Cell 5: Define SV model and Bootstrap PF ---
    nb.cells.append(new_markdown_cell(
        "## 3. Particle Filtering of Latent Volatility\n"
        "\n"
        "We define the basic SV model and run a **Bootstrap Particle Filter** with $N=1000$ particles "
        "to estimate the latent log-volatility path $\\{h_t\\}$."
    ))
    nb.cells.append(new_code_cell(
        "# Define basic SV model\n"
        "sv_model = StochasticVolatility(variant='basic')\n"
        "print('Default parameters:', sv_model.params)\n"
        "print(f'k_states={sv_model.k_states}, k_obs={sv_model.k_obs}')\n"
        "\n"
        "# Bootstrap Particle Filter (vectorized)\n"
        "def bootstrap_pf_sv(\n"
        "    y: np.ndarray,\n"
        "    mu: float, phi: float, sigma: float,\n"
        "    n_particles: int = 1000,\n"
        "    seed: int = 42,\n"
        ") -> dict:\n"
        "    \"\"\"Run bootstrap PF on basic SV model. Returns filtered means, stds, and log-likelihood.\"\"\"\n"
        "    rng = np.random.default_rng(seed)\n"
        "    T = len(y)\n"
        "    \n"
        "    # Stationary distribution\n"
        "    var_stat = sigma**2 / (1.0 - phi**2)\n"
        "    particles = rng.normal(mu, np.sqrt(var_stat), size=n_particles)\n"
        "    \n"
        "    filtered_means = np.zeros(T)\n"
        "    filtered_stds = np.zeros(T)\n"
        "    filtered_q05 = np.zeros(T)\n"
        "    filtered_q95 = np.zeros(T)\n"
        "    ess_history = np.zeros(T)\n"
        "    log_lik = 0.0\n"
        "    \n"
        "    for t in range(T):\n"
        "        # Weights\n"
        "        vol = np.exp(particles / 2.0)\n"
        "        log_w = -0.5 * np.log(2 * np.pi) - np.log(vol) - 0.5 * (y[t] / vol)**2\n"
        "        max_lw = np.max(log_w)\n"
        "        w = np.exp(log_w - max_lw)\n"
        "        sw = np.sum(w)\n"
        "        log_lik += max_lw + np.log(sw) - np.log(n_particles)\n"
        "        w /= sw\n"
        "        \n"
        "        # Store\n"
        "        filtered_means[t] = np.sum(w * particles)\n"
        "        filtered_stds[t] = np.sqrt(np.sum(w * (particles - filtered_means[t])**2))\n"
        "        \n"
        "        # Weighted quantiles\n"
        "        idx_sort = np.argsort(particles)\n"
        "        cumw = np.cumsum(w[idx_sort])\n"
        "        filtered_q05[t] = particles[idx_sort][np.searchsorted(cumw, 0.05)]\n"
        "        filtered_q95[t] = particles[idx_sort][np.searchsorted(cumw, 0.95, side='right').clip(max=n_particles-1)]\n"
        "        ess_history[t] = 1.0 / np.sum(w**2)\n"
        "        \n"
        "        # Resample and propagate\n"
        "        idx = rng.choice(n_particles, size=n_particles, p=w)\n"
        "        particles = particles[idx]\n"
        "        particles = mu + phi * (particles - mu) + sigma * rng.standard_normal(n_particles)\n"
        "    \n"
        "    return {\n"
        "        'means': filtered_means,\n"
        "        'stds': filtered_stds,\n"
        "        'q05': filtered_q05,\n"
        "        'q95': filtered_q95,\n"
        "        'ess': ess_history,\n"
        "        'log_likelihood': log_lik,\n"
        "    }\n"
        "\n"
        "# Run with default parameters\n"
        "t0 = time.time()\n"
        "pf_result = bootstrap_pf_sv(\n"
        "    returns, mu=-1.0, phi=0.97, sigma=0.15, n_particles=1000, seed=42\n"
        ")\n"
        "elapsed = time.time() - t0\n"
        "print(f'Bootstrap PF completed in {elapsed:.2f}s')\n"
        "print(f'Log-likelihood: {pf_result[\"log_likelihood\"]:.2f}')\n"
        "print(f'Mean ESS: {pf_result[\"ess\"].mean():.0f} / 1000')"
    ))

    # --- Cell 6: Plot filtered volatility with bands ---
    nb.cells.append(new_markdown_cell(
        "## 4. Filtered Volatility with Confidence Bands\n"
        "\n"
        "We overlay the filtered volatility $\\exp(h_t/2)$ on the absolute returns, "
        "with 90% posterior credible bands."
    ))
    nb.cells.append(new_code_cell(
        "fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)\n"
        "\n"
        "# Panel 1: Returns\n"
        "axes[0].plot(dates, returns, linewidth=0.5, color='steelblue')\n"
        "axes[0].set_title('Returns')\n"
        "axes[0].axhline(0, color='k', linewidth=0.5)\n"
        "axes[0].set_ylabel('$y_t$')\n"
        "\n"
        "# Panel 2: Filtered log-volatility with bands\n"
        "h_mean = pf_result['means']\n"
        "h_q05 = pf_result['q05']\n"
        "h_q95 = pf_result['q95']\n"
        "axes[1].plot(dates, h_mean, color='darkred', linewidth=1.2, label='$E[h_t | y_{1:t}]$')\n"
        "axes[1].fill_between(dates, h_q05, h_q95, alpha=0.3, color='salmon', label='90% CI')\n"
        "axes[1].set_title('Filtered Log-Volatility $h_t$')\n"
        "axes[1].set_ylabel('$h_t$')\n"
        "axes[1].legend()\n"
        "\n"
        "# Panel 3: Filtered volatility vs absolute returns\n"
        "vol_mean = np.exp(h_mean / 2.0)\n"
        "vol_q05 = np.exp(h_q05 / 2.0)\n"
        "vol_q95 = np.exp(h_q95 / 2.0)\n"
        "axes[2].plot(dates, np.abs(returns), linewidth=0.4, color='grey', alpha=0.6, label='|returns|')\n"
        "axes[2].plot(dates, vol_mean, color='darkred', linewidth=1.5, label='Filtered $\\\\exp(h_t/2)$')\n"
        "axes[2].fill_between(dates, vol_q05, vol_q95, alpha=0.3, color='salmon', label='90% CI')\n"
        "axes[2].set_title('Filtered Volatility vs Absolute Returns')\n"
        "axes[2].set_ylabel('Volatility')\n"
        "axes[2].legend()\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    # --- Cell 7: PMMH estimation ---
    nb.cells.append(new_markdown_cell(
        "## 5. Parameter Estimation via PMMH\n"
        "\n"
        "Particle Marginal Metropolis–Hastings uses the particle filter log-likelihood "
        "as an unbiased estimator inside a Metropolis–Hastings chain to sample from "
        "$p(\\mu, \\phi, \\sigma \\mid y_{1:T})$.\n"
        "\n"
        "We run a short chain for demonstration."
    ))
    nb.cells.append(new_code_cell(
        "# Model wrapper for PMMH\n"
        "@dataclass\n"
        "class FilterResult:\n"
        "    log_likelihood: float\n"
        "    filtered_means: np.ndarray | None = None\n"
        "\n"
        "class SVModelWrapper:\n"
        "    def __init__(self) -> None:\n"
        "        self.sv = StochasticVolatility(variant='basic')\n"
        "        self.param_names = list(self.sv.param_names)  # ['mu', 'phi', 'sigma']\n"
        "        self._rng_internal = np.random.default_rng(0)\n"
        "\n"
        "    def set_params(self, theta: np.ndarray) -> None:\n"
        "        for i, name in enumerate(self.param_names):\n"
        "            self.sv.params[name] = float(theta[i])\n"
        "\n"
        "    def get_params(self) -> np.ndarray:\n"
        "        return np.array([self.sv.params[n] for n in self.param_names])\n"
        "\n"
        "    def filter(self, endog, n_particles=200, rng=None):\n"
        "        if rng is None:\n"
        "            rng = self._rng_internal\n"
        "        T = len(endog)\n"
        "        mu = self.sv.params['mu']\n"
        "        phi = self.sv.params['phi']\n"
        "        sigma = self.sv.params['sigma']\n"
        "        if abs(phi) >= 1.0 or sigma <= 0:\n"
        "            return FilterResult(log_likelihood=-np.inf)\n"
        "        var_stat = sigma**2 / (1.0 - phi**2)\n"
        "        particles = rng.normal(mu, np.sqrt(max(var_stat, 1e-10)), size=n_particles)\n"
        "        log_lik = 0.0\n"
        "        for t in range(T):\n"
        "            vol = np.exp(particles / 2.0)\n"
        "            log_w = -0.5 * np.log(2 * np.pi) - np.log(vol) - 0.5 * (endog[t] / vol)**2\n"
        "            max_lw = np.max(log_w)\n"
        "            w = np.exp(log_w - max_lw)\n"
        "            sw = np.sum(w)\n"
        "            if sw < 1e-300:\n"
        "                return FilterResult(log_likelihood=-np.inf)\n"
        "            log_lik += max_lw + np.log(sw) - np.log(n_particles)\n"
        "            w /= sw\n"
        "            idx = rng.choice(n_particles, size=n_particles, p=w)\n"
        "            particles = particles[idx]\n"
        "            particles = mu + phi * (particles - mu) + sigma * rng.standard_normal(n_particles)\n"
        "        return FilterResult(log_likelihood=log_lik)\n"
        "\n"
        "    def initial_sample(self, n, rng):\n"
        "        mu, phi, sigma = self.sv.params['mu'], self.sv.params['phi'], self.sv.params['sigma']\n"
        "        if abs(phi) >= 1.0 or sigma <= 0:\n"
        "            return rng.standard_normal(n)\n"
        "        return rng.normal(mu, np.sqrt(sigma**2 / (1.0 - phi**2)), size=n)\n"
        "\n"
        "    def transition_sample(self, x_prev, rng):\n"
        "        mu, phi, sigma = self.sv.params['mu'], self.sv.params['phi'], self.sv.params['sigma']\n"
        "        return float(mu + phi * (float(x_prev) - mu) + sigma * rng.standard_normal())\n"
        "\n"
        "    def transition_logpdf(self, x_new, x_old):\n"
        "        mu, phi, sigma = self.sv.params['mu'], self.sv.params['phi'], self.sv.params['sigma']\n"
        "        if sigma <= 0: return -np.inf\n"
        "        return float(stats.norm.logpdf(float(x_new), loc=mu + phi * (float(x_old) - mu), scale=sigma))\n"
        "\n"
        "    def observation_logpdf(self, y, x):\n"
        "        h = float(x)\n"
        "        vol = np.exp(h / 2.0)\n"
        "        if vol < 1e-300: return -np.inf\n"
        "        return float(-0.5 * np.log(2 * np.pi) - np.log(vol) - 0.5 * (float(y) / vol)**2)\n"
        "\n"
        "# Prior\n"
        "class SVPrior:\n"
        "    def logpdf(self, theta):\n"
        "        mu_val, phi_val, sig_val = theta[0], theta[1], theta[2]\n"
        "        if not (0 < phi_val < 1) or sig_val <= 0:\n"
        "            return -np.inf\n"
        "        lp = float(stats.norm.logpdf(mu_val, loc=-1, scale=1))\n"
        "        lp += float(stats.beta.logpdf(phi_val, 20, 1.5))\n"
        "        lp += float(stats.invgamma.logpdf(sig_val, a=2.5, scale=0.025))\n"
        "        return lp\n"
        "\n"
        "    def sample(self, rng):\n"
        "        mu_s = rng.normal(-1, 1)\n"
        "        phi_s = float(stats.beta.rvs(20, 1.5, random_state=rng))\n"
        "        sig_s = float(stats.invgamma.rvs(2.5, scale=0.025, random_state=rng))\n"
        "        return np.array([mu_s, phi_s, sig_s])\n"
        "\n"
        "    @property\n"
        "    def cov(self):\n"
        "        return np.array([1.0, 20*1.5/((21.5)**2*22.5), 0.025**2/(1.5**2*0.5)])\n"
        "\n"
        "# Run PMMH\n"
        "model_wrapper = SVModelWrapper()\n"
        "prior = SVPrior()\n"
        "\n"
        "# Use first 200 obs for fast demo\n"
        "y_pmmh = returns[:200]\n"
        "\n"
        "pmmh = PMMH(\n"
        "    model=model_wrapper,\n"
        "    prior=prior,\n"
        "    n_particles=200,\n"
        "    n_iterations=2000,\n"
        "    proposal_cov='adaptive',\n"
        "    target_acceptance=0.234,\n"
        "    burnin=500,\n"
        "    thin=1,\n"
        "    seed=42,\n"
        ")\n"
        "\n"
        "print('Running PMMH (N=200, 2000 iterations)...')\n"
        "t0 = time.time()\n"
        "pmmh_results = pmmh.run(endog=y_pmmh, theta_init=np.array([-1.0, 0.97, 0.15]), verbose=500)\n"
        "elapsed = time.time() - t0\n"
        "print(f'Completed in {elapsed:.1f}s')\n"
        "print(f'Acceptance rate: {pmmh_results.acceptance_rate():.3f}')\n"
        "print(pmmh_results.summary())"
    ))

    # --- Cell 8: Plot posteriors ---
    nb.cells.append(new_markdown_cell(
        "## 6. Posterior Distributions"
    ))
    nb.cells.append(new_code_cell(
        "samples = pmmh_results.posterior_samples\n"
        "param_names = ['$\\\\mu$', '$\\\\phi$', '$\\\\sigma_h$']\n"
        "true_vals = [-1.0, 0.97, 0.15]  # defaults used for filtering\n"
        "\n"
        "fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n"
        "for i, (ax, name, true_v) in enumerate(zip(axes, param_names, true_vals)):\n"
        "    ax.hist(samples[:, i], bins=40, density=True, alpha=0.7, color='steelblue')\n"
        "    ax.axvline(true_v, color='red', linestyle='--', linewidth=2, label=f'Default: {true_v}')\n"
        "    ax.axvline(samples[:, i].mean(), color='orange', linestyle='-', linewidth=2,\n"
        "              label=f'Post. mean: {samples[:, i].mean():.3f}')\n"
        "    ax.set_title(f'Posterior of {name}')\n"
        "    ax.legend(fontsize=8)\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "# Trace plots\n"
        "fig, axes = plt.subplots(3, 1, figsize=(14, 6), sharex=True)\n"
        "raw_names = ['mu', 'phi', 'sigma_h']\n"
        "chains = pmmh_results.chains\n"
        "for i, (ax, name) in enumerate(zip(axes, raw_names)):\n"
        "    ax.plot(chains[:, i], linewidth=0.5, color='steelblue')\n"
        "    ax.axhline(true_vals[i], color='red', linestyle='--', linewidth=1)\n"
        "    ax.set_ylabel(name)\n"
        "axes[-1].set_xlabel('Iteration')\n"
        "axes[0].set_title('PMMH Trace Plots')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    # --- Cell 9: Forecasting ---
    nb.cells.append(new_markdown_cell(
        "## 7. Volatility Forecasting\n"
        "\n"
        "We forecast the log-volatility $h$-steps ahead by propagating particles forward "
        "from the last filtered distribution."
    ))
    nb.cells.append(new_code_cell(
        "# Forecast using posterior mean parameters\n"
        "post_mean = pmmh_results.posterior_mean()\n"
        "mu_hat, phi_hat, sig_hat = post_mean[0], post_mean[1], post_mean[2]\n"
        "print(f'Posterior mean params: mu={mu_hat:.3f}, phi={phi_hat:.3f}, sigma={sig_hat:.3f}')\n"
        "\n"
        "# Re-run filter to get final particle cloud\n"
        "rng_fc = np.random.default_rng(123)\n"
        "N_fc = 2000\n"
        "var_stat = sig_hat**2 / (1.0 - phi_hat**2)\n"
        "particles_fc = rng_fc.normal(mu_hat, np.sqrt(max(var_stat, 1e-10)), size=N_fc)\n"
        "\n"
        "for t in range(T_use):\n"
        "    vol = np.exp(particles_fc / 2.0)\n"
        "    log_w = -0.5 * np.log(2 * np.pi) - np.log(vol) - 0.5 * (returns[t] / vol)**2\n"
        "    max_lw = np.max(log_w)\n"
        "    w = np.exp(log_w - max_lw)\n"
        "    w /= np.sum(w)\n"
        "    idx = rng_fc.choice(N_fc, size=N_fc, p=w)\n"
        "    particles_fc = particles_fc[idx]\n"
        "    particles_fc = mu_hat + phi_hat * (particles_fc - mu_hat) + sig_hat * rng_fc.standard_normal(N_fc)\n"
        "\n"
        "# Now forecast H steps ahead\n"
        "H = 30\n"
        "forecast_mean = np.zeros(H)\n"
        "forecast_q05 = np.zeros(H)\n"
        "forecast_q95 = np.zeros(H)\n"
        "particles_ahead = particles_fc.copy()\n"
        "\n"
        "for h in range(H):\n"
        "    # Propagate one step without observations\n"
        "    particles_ahead = mu_hat + phi_hat * (particles_ahead - mu_hat) + sig_hat * rng_fc.standard_normal(N_fc)\n"
        "    forecast_mean[h] = np.mean(particles_ahead)\n"
        "    forecast_q05[h] = np.percentile(particles_ahead, 5)\n"
        "    forecast_q95[h] = np.percentile(particles_ahead, 95)\n"
        "\n"
        "# Plot: filtered + forecast\n"
        "fig, ax = plt.subplots(figsize=(14, 5))\n"
        "n_show = 100\n"
        "t_past = np.arange(T_use - n_show, T_use)\n"
        "t_future = np.arange(T_use, T_use + H)\n"
        "\n"
        "ax.plot(t_past, pf_result['means'][-n_show:], color='darkred', linewidth=1.5, label='Filtered $h_t$')\n"
        "ax.fill_between(t_past, pf_result['q05'][-n_show:], pf_result['q95'][-n_show:],\n"
        "                alpha=0.2, color='salmon')\n"
        "ax.plot(t_future, forecast_mean, color='darkblue', linewidth=1.5, label='Forecast $h_{t+k}$')\n"
        "ax.fill_between(t_future, forecast_q05, forecast_q95, alpha=0.2, color='cornflowerblue', label='90% PI')\n"
        "ax.axvline(T_use, color='k', linestyle=':', linewidth=1)\n"
        "ax.set_xlabel('Time')\n"
        "ax.set_ylabel('$h_t$')\n"
        "ax.set_title('Filtered Volatility + Forecast')\n"
        "ax.legend()\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    # --- Cell 10: Summary table ---
    nb.cells.append(new_markdown_cell(
        "## 8. Parameter Summary"
    ))
    nb.cells.append(new_code_cell(
        "post_mean = pmmh_results.posterior_mean()\n"
        "post_std = pmmh_results.posterior_std()\n"
        "ci_low, ci_high = pmmh_results.credible_interval(alpha=0.05)\n"
        "\n"
        "summary_df = pd.DataFrame({\n"
        "    'Parameter': ['mu', 'phi', 'sigma_h'],\n"
        "    'Default': [-1.0, 0.97, 0.15],\n"
        "    'Posterior Mean': post_mean,\n"
        "    'Posterior Std': post_std,\n"
        "    '95% CI Low': ci_low,\n"
        "    '95% CI High': ci_high,\n"
        "    'ESS': [pmmh_results.effective_sample_size(i) for i in range(3)],\n"
        "})\n"
        "print(summary_df.to_string(index=False))\n"
        "summary_df"
    ))

    # --- Cell 11: Conclusions ---
    nb.cells.append(new_markdown_cell(
        "## Summary\n"
        "\n"
        "- The **Bootstrap Particle Filter** successfully recovers the latent log-volatility path\n"
        "- The **ACF of squared returns** confirms volatility clustering, motivating the SV model\n"
        "- **PMMH** estimates the posterior of $(\\mu, \\phi, \\sigma)$ — the high persistence\n"
        "  $\\phi \\approx 0.97$ is a hallmark of financial volatility\n"
        "- **Forecasts** revert toward the unconditional mean with growing uncertainty bands\n"
        "\n"
        "Next: [02_sv_leverage.ipynb](02_sv_leverage.ipynb) — adding leverage effects"
    ))

    return nb


# ============================================================================
# Notebook 2: SV Leverage
# ============================================================================

def build_nb2() -> nbf.NotebookNode:
    """02_sv_leverage.ipynb — SV with leverage effect."""
    nb = new_notebook()
    nb.metadata.kernelspec = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }

    # --- Cell 1: Title ---
    nb.cells.append(new_markdown_cell(
        "# Stochastic Volatility with Leverage\n"
        "\n"
        "The **leverage effect** refers to the negative correlation between returns and future "
        "volatility: negative shocks increase volatility more than positive shocks of the same size.\n"
        "\n"
        "The SV-L model introduces correlation $\\rho < 0$ between the return and volatility innovations:\n"
        "$$y_t = \\exp(h_t/2)\\,\\varepsilon_t, \\qquad "
        "h_{t+1} = \\mu + \\phi\\,(h_t - \\mu) + \\sigma\\,\\eta_t$$\n"
        "where $\\text{Corr}(\\varepsilon_t, \\eta_{t+1}) = \\rho$.\n"
        "\n"
        "We estimate the model using **Particle Gibbs with Ancestor Sampling (PGAS)**."
    ))

    # --- Cell 2: Imports ---
    nb.cells.append(new_code_cell(
        "import sys, os\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "%matplotlib inline\n"
        "from scipy import stats\n"
        "from dataclasses import dataclass\n"
        "import time\n"
        "\n"
        "sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..', '..', '..')))\n"
        "\n"
        "from particlefilterbox.models.stochastic_volatility import StochasticVolatility\n"
        "from particlefilterbox.pmcmc import PGAS\n"
        "\n"
        "plt.rcParams['figure.figsize'] = (12, 5)\n"
        "plt.rcParams['figure.dpi'] = 100\n"
        "np.random.seed(42)"
    ))

    # --- Cell 3: Load data ---
    nb.cells.append(new_markdown_cell(
        "## 1. Data Loading and Empirical Evidence of Leverage"
    ))
    nb.cells.append(new_code_cell(
        "data_path = os.path.join('..', 'data', 'simulated_sv_leverage.csv')\n"
        "df = pd.read_csv(data_path)\n"
        "print(f'Loaded {len(df)} observations')\n"
        "print(df.head())\n"
        "\n"
        "T_use = 200\n"
        "y_obs = df['y_obs'].values[:T_use]\n"
        "h_true = df['h_true'].values[:T_use]\n"
        "\n"
        "# True parameters used in simulation\n"
        "true_params = {'mu': -1.0, 'phi': 0.97, 'sigma': 0.15, 'rho': -0.5}\n"
        "print(f'True parameters: {true_params}')"
    ))

    # --- Cell 4: Empirical evidence of leverage ---
    nb.cells.append(new_code_cell(
        "# Empirical evidence: correlation between returns and future squared returns\n"
        "fig, axes = plt.subplots(1, 3, figsize=(15, 4))\n"
        "\n"
        "# Plot 1: Returns time series\n"
        "axes[0].plot(y_obs, linewidth=0.5, color='steelblue')\n"
        "axes[0].set_title('Simulated Returns (SV-Leverage)')\n"
        "axes[0].set_xlabel('Time')\n"
        "axes[0].set_ylabel('$y_t$')\n"
        "axes[0].axhline(0, color='k', linewidth=0.5)\n"
        "\n"
        "# Plot 2: Return vs next-period squared return (leverage evidence)\n"
        "axes[1].scatter(y_obs[:-1], y_obs[1:]**2, alpha=0.3, s=10, color='steelblue')\n"
        "# Add regression line\n"
        "from numpy.polynomial.polynomial import polyfit\n"
        "b, m = polyfit(y_obs[:-1], y_obs[1:]**2, 1)\n"
        "x_line = np.linspace(y_obs.min(), y_obs.max(), 100)\n"
        "axes[1].plot(x_line, b + m * x_line, 'r-', linewidth=2)\n"
        "axes[1].set_title(f'Leverage: $y_t$ vs $y_{{t+1}}^2$ (slope={m:.4f})')\n"
        "axes[1].set_xlabel('$y_t$')\n"
        "axes[1].set_ylabel('$y_{t+1}^2$')\n"
        "\n"
        "# Plot 3: Cross-correlation function\n"
        "max_lag = 15\n"
        "sq_y = y_obs ** 2\n"
        "ccf = np.array([\n"
        "    np.corrcoef(y_obs[:T_use-lag], sq_y[lag:])[0, 1]\n"
        "    for lag in range(1, max_lag + 1)\n"
        "])\n"
        "axes[2].bar(range(1, max_lag + 1), ccf, color='steelblue')\n"
        "axes[2].axhline(0, color='k', linewidth=0.5)\n"
        "axes[2].set_title('Cross-correlation: $y_t$ and $y_{t+k}^2$')\n"
        "axes[2].set_xlabel('Lag $k$')\n"
        "axes[2].set_ylabel('Correlation')\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "print(f'Corr(y_t, y_{{t+1}}^2) = {ccf[0]:.4f} (negative → leverage effect)')"
    ))

    # --- Cell 5: Define SV-L model and filter ---
    nb.cells.append(new_markdown_cell(
        "## 2. Bootstrap Particle Filter on SV-Leverage\n"
        "\n"
        "We first filter with the basic SV model (ignoring leverage) and the SV-L model "
        "to compare log-likelihoods."
    ))
    nb.cells.append(new_code_cell(
        "def bootstrap_pf_sv_leverage(\n"
        "    y: np.ndarray,\n"
        "    mu: float, phi: float, sigma: float, rho: float = 0.0,\n"
        "    n_particles: int = 1000, seed: int = 42,\n"
        ") -> dict:\n"
        "    \"\"\"Bootstrap PF for SV model (optionally with leverage).\"\"\"\n"
        "    rng = np.random.default_rng(seed)\n"
        "    T = len(y)\n"
        "    var_stat = sigma**2 / (1.0 - phi**2)\n"
        "    particles = rng.normal(mu, np.sqrt(max(var_stat, 1e-10)), size=n_particles)\n"
        "    \n"
        "    filtered_means = np.zeros(T)\n"
        "    filtered_stds = np.zeros(T)\n"
        "    filtered_q05 = np.zeros(T)\n"
        "    filtered_q95 = np.zeros(T)\n"
        "    log_lik = 0.0\n"
        "    var_cond = max(1.0 - rho**2, 1e-10)\n"
        "    etas = np.zeros(n_particles)  # transition innovations\n"
        "    \n"
        "    for t in range(T):\n"
        "        vol = np.exp(particles / 2.0)\n"
        "        eps = y[t] / vol\n"
        "        if t == 0 or abs(rho) < 1e-10:\n"
        "            log_w = -0.5 * np.log(2 * np.pi) - np.log(vol) - 0.5 * eps**2\n"
        "        else:\n"
        "            mean_cond = rho * etas\n"
        "            log_w = (-0.5 * np.log(2 * np.pi * var_cond)\n"
        "                     - 0.5 * (eps - mean_cond)**2 / var_cond - np.log(vol))\n"
        "        max_lw = np.max(log_w)\n"
        "        w = np.exp(log_w - max_lw)\n"
        "        sw = np.sum(w)\n"
        "        if sw < 1e-300:\n"
        "            return {'means': filtered_means, 'stds': filtered_stds,\n"
        "                    'q05': filtered_q05, 'q95': filtered_q95, 'log_likelihood': -np.inf}\n"
        "        log_lik += max_lw + np.log(sw) - np.log(n_particles)\n"
        "        w /= sw\n"
        "        filtered_means[t] = np.sum(w * particles)\n"
        "        filtered_stds[t] = np.sqrt(np.sum(w * (particles - filtered_means[t])**2))\n"
        "        idx_sort = np.argsort(particles)\n"
        "        cumw = np.cumsum(w[idx_sort])\n"
        "        filtered_q05[t] = particles[idx_sort][np.searchsorted(cumw, 0.05)]\n"
        "        filtered_q95[t] = particles[idx_sort][np.searchsorted(cumw, 0.95, side='right').clip(max=n_particles-1)]\n"
        "        \n"
        "        idx = rng.choice(n_particles, size=n_particles, p=w)\n"
        "        particles = particles[idx]\n"
        "        etas = rng.standard_normal(n_particles)\n"
        "        particles = mu + phi * (particles - mu) + sigma * etas\n"
        "    \n"
        "    return {\n"
        "        'means': filtered_means, 'stds': filtered_stds,\n"
        "        'q05': filtered_q05, 'q95': filtered_q95, 'log_likelihood': log_lik\n"
        "    }\n"
        "\n"
        "# Compare SV basic vs SV-L\n"
        "result_basic = bootstrap_pf_sv_leverage(y_obs, mu=-1.0, phi=0.97, sigma=0.15, rho=0.0,\n"
        "                                        n_particles=1000, seed=42)\n"
        "result_leverage = bootstrap_pf_sv_leverage(y_obs, mu=-1.0, phi=0.97, sigma=0.15, rho=-0.5,\n"
        "                                           n_particles=1000, seed=42)\n"
        "\n"
        "print(f'Log-likelihood (SV basic): {result_basic[\"log_likelihood\"]:.2f}')\n"
        "print(f'Log-likelihood (SV-L):     {result_leverage[\"log_likelihood\"]:.2f}')\n"
        "print(f'Difference:                {result_leverage[\"log_likelihood\"] - result_basic[\"log_likelihood\"]:.2f}')"
    ))

    # --- Cell 6: PGAS estimation ---
    nb.cells.append(new_markdown_cell(
        "## 3. Parameter Estimation via PGAS\n"
        "\n"
        "PGAS (Particle Gibbs with Ancestor Sampling) is especially well-suited for "
        "joint state-parameter inference in nonlinear state-space models."
    ))
    nb.cells.append(new_code_cell(
        "# Model wrapper for PGAS (leverage variant)\n"
        "@dataclass\n"
        "class FilterResult:\n"
        "    log_likelihood: float\n"
        "    filtered_means: np.ndarray | None = None\n"
        "\n"
        "class SVLeverageWrapper:\n"
        "    def __init__(self):\n"
        "        self.sv = StochasticVolatility(variant='leverage')\n"
        "        self.param_names = list(self.sv.param_names)  # ['mu', 'phi', 'sigma', 'rho']\n"
        "        self._rng_internal = np.random.default_rng(0)\n"
        "\n"
        "    def set_params(self, theta):\n"
        "        for i, name in enumerate(self.param_names):\n"
        "            self.sv.params[name] = float(theta[i])\n"
        "\n"
        "    def get_params(self):\n"
        "        return np.array([self.sv.params[n] for n in self.param_names])\n"
        "\n"
        "    def filter(self, endog, n_particles=200, rng=None):\n"
        "        if rng is None: rng = self._rng_internal\n"
        "        T = len(endog)\n"
        "        mu, phi = self.sv.params['mu'], self.sv.params['phi']\n"
        "        sigma, rho = self.sv.params['sigma'], self.sv.params.get('rho', 0.0)\n"
        "        if abs(phi) >= 1.0 or sigma <= 0:\n"
        "            return FilterResult(log_likelihood=-np.inf)\n"
        "        var_stat = sigma**2 / (1.0 - phi**2)\n"
        "        particles = rng.normal(mu, np.sqrt(max(var_stat, 1e-10)), size=n_particles)\n"
        "        log_lik = 0.0\n"
        "        var_cond = max(1.0 - rho**2, 1e-10)\n"
        "        etas = np.zeros(n_particles)\n"
        "        filtered_h = np.zeros(T)\n"
        "        filtered_eta = np.zeros(T)\n"
        "        for t in range(T):\n"
        "            vol = np.exp(particles / 2.0)\n"
        "            eps = endog[t] / vol\n"
        "            if t == 0:\n"
        "                log_w = -0.5 * np.log(2 * np.pi) - np.log(vol) - 0.5 * eps**2\n"
        "            else:\n"
        "                mean_cond = rho * etas\n"
        "                log_w = (-0.5 * np.log(2 * np.pi * var_cond)\n"
        "                         - 0.5 * (eps - mean_cond)**2 / var_cond - np.log(vol))\n"
        "            max_lw = np.max(log_w)\n"
        "            w = np.exp(log_w - max_lw)\n"
        "            sw = np.sum(w)\n"
        "            if sw < 1e-300:\n"
        "                return FilterResult(log_likelihood=-np.inf)\n"
        "            log_lik += max_lw + np.log(sw) - np.log(n_particles)\n"
        "            w /= sw\n"
        "            filtered_h[t] = np.sum(w * particles)\n"
        "            filtered_eta[t] = np.sum(w * etas)\n"
        "            idx = rng.choice(n_particles, size=n_particles, p=w)\n"
        "            particles = particles[idx]\n"
        "            etas = rng.standard_normal(n_particles)\n"
        "            particles = mu + phi * (particles - mu) + sigma * etas\n"
        "        filtered_means = np.column_stack([filtered_h, filtered_eta])\n"
        "        return FilterResult(log_likelihood=log_lik, filtered_means=filtered_means)\n"
        "\n"
        "    def initial_sample(self, n, rng):\n"
        "        mu, phi, sigma = self.sv.params['mu'], self.sv.params['phi'], self.sv.params['sigma']\n"
        "        if abs(phi) >= 1.0 or sigma <= 0:\n"
        "            return np.column_stack([rng.standard_normal(n), np.zeros(n)])\n"
        "        var_stat = sigma**2 / (1.0 - phi**2)\n"
        "        h_init = rng.normal(mu, np.sqrt(max(var_stat, 1e-10)), size=n)\n"
        "        return np.column_stack([h_init, np.zeros(n)])\n"
        "\n"
        "    def transition_sample(self, x_prev, rng):\n"
        "        mu, phi, sigma = self.sv.params['mu'], self.sv.params['phi'], self.sv.params['sigma']\n"
        "        h_prev = float(x_prev[0]) if hasattr(x_prev, '__getitem__') else float(x_prev)\n"
        "        eta = float(rng.standard_normal())\n"
        "        h_new = mu + phi * (h_prev - mu) + sigma * eta\n"
        "        return np.array([h_new, eta])\n"
        "\n"
        "    def transition_logpdf(self, x_new, x_old):\n"
        "        mu, phi, sigma = self.sv.params['mu'], self.sv.params['phi'], self.sv.params['sigma']\n"
        "        if sigma <= 0: return -np.inf\n"
        "        h_new = float(x_new[0]) if hasattr(x_new, '__getitem__') else float(x_new)\n"
        "        h_old = float(x_old[0]) if hasattr(x_old, '__getitem__') else float(x_old)\n"
        "        return float(stats.norm.logpdf(h_new, loc=mu + phi * (h_old - mu), scale=sigma))\n"
        "\n"
        "    def observation_logpdf(self, y, x):\n"
        "        h = float(x[0]) if hasattr(x, '__getitem__') else float(x)\n"
        "        eta = float(x[1]) if (hasattr(x, '__getitem__') and len(x) > 1) else 0.0\n"
        "        rho = self.sv.params.get('rho', 0.0)\n"
        "        vol = np.exp(h / 2.0)\n"
        "        if vol < 1e-300: return -np.inf\n"
        "        eps = float(y) / vol\n"
        "        var_cond = max(1.0 - rho**2, 1e-10)\n"
        "        mean_cond = rho * eta\n"
        "        return float(-0.5 * np.log(2 * np.pi * var_cond)\n"
        "                     - 0.5 * (eps - mean_cond)**2 / var_cond - np.log(vol))\n"
        "\n"
        "# Prior with rho\n"
        "class SVLeveragePrior:\n"
        "    def logpdf(self, theta):\n"
        "        mu_val, phi_val, sig_val, rho_val = theta[0], theta[1], theta[2], theta[3]\n"
        "        if not (0 < phi_val < 1) or sig_val <= 0 or not (-1 < rho_val < 1):\n"
        "            return -np.inf\n"
        "        lp = float(stats.norm.logpdf(mu_val, loc=-1, scale=1))\n"
        "        lp += float(stats.beta.logpdf(phi_val, 20, 1.5))\n"
        "        lp += float(stats.invgamma.logpdf(sig_val, a=2.5, scale=0.025))\n"
        "        lp += float(stats.uniform.logpdf(rho_val, loc=-1.0, scale=2.0))\n"
        "        return lp\n"
        "\n"
        "    def sample(self, rng):\n"
        "        mu_s = rng.normal(-1, 1)\n"
        "        phi_s = float(stats.beta.rvs(20, 1.5, random_state=rng))\n"
        "        sig_s = float(stats.invgamma.rvs(2.5, scale=0.025, random_state=rng))\n"
        "        rho_s = rng.uniform(-1.0, 1.0)\n"
        "        return np.array([mu_s, phi_s, sig_s, rho_s])\n"
        "\n"
        "    @property\n"
        "    def cov(self):\n"
        "        return np.array([1.0, 20*1.5/((21.5)**2*22.5), 0.025**2/(1.5**2*0.5), 1.0/3.0])\n"
        "\n"
        "# Parameter sampler for PGAS\n"
        "def sv_leverage_param_sampler(model, states, endog, theta_current, rng):\n"
        "    prior = SVLeveragePrior()\n"
        "    step_sizes = np.array([0.05, 0.01, 0.01, 0.05])\n"
        "    theta = theta_current.copy()\n"
        "    for _ in range(3):\n"
        "        for j in range(len(theta)):\n"
        "            theta_prop = theta.copy()\n"
        "            theta_prop[j] += step_sizes[j] * rng.standard_normal()\n"
        "            lp_prop = prior.logpdf(theta_prop)\n"
        "            if not np.isfinite(lp_prop): continue\n"
        "            lp_curr = prior.logpdf(theta)\n"
        "            ll_curr = _cond_loglik(endog, states, theta)\n"
        "            ll_prop = _cond_loglik(endog, states, theta_prop)\n"
        "            log_alpha = (lp_prop + ll_prop) - (lp_curr + ll_curr)\n"
        "            if np.log(rng.random()) < log_alpha:\n"
        "                theta = theta_prop\n"
        "    return theta\n"
        "\n"
        "def _cond_loglik(endog, states, theta):\n"
        "    mu, phi, sigma, rho = theta[0], theta[1], theta[2], theta[3]\n"
        "    if abs(phi) >= 1.0 or sigma <= 0 or abs(rho) >= 1.0:\n"
        "        return -np.inf\n"
        "    T = len(endog)\n"
        "    loglik = 0.0\n"
        "    var_cond = max(1.0 - rho**2, 1e-10)\n"
        "    if states.ndim == 2:\n"
        "        h_vals, eta_vals = states[:, 0], states[:, 1]\n"
        "    else:\n"
        "        h_vals, eta_vals = states, np.zeros(T)\n"
        "    var_stat = sigma**2 / (1.0 - phi**2)\n"
        "    loglik += float(stats.norm.logpdf(h_vals[0], loc=mu, scale=np.sqrt(var_stat)))\n"
        "    for t in range(T):\n"
        "        h_t = float(h_vals[t])\n"
        "        vol = np.exp(h_t / 2.0)\n"
        "        if vol < 1e-300: return -np.inf\n"
        "        eps = endog[t] / vol\n"
        "        if t == 0:\n"
        "            loglik += -0.5 * np.log(2 * np.pi) - np.log(vol) - 0.5 * eps**2\n"
        "        else:\n"
        "            mean_cond = rho * eta_vals[t]\n"
        "            loglik += (-0.5 * np.log(2 * np.pi * var_cond)\n"
        "                       - 0.5 * (eps - mean_cond)**2 / var_cond - np.log(vol))\n"
        "        if t < T - 1:\n"
        "            loglik += float(stats.norm.logpdf(h_vals[t + 1], loc=mu + phi * (h_t - mu), scale=sigma))\n"
        "    return loglik\n"
        "\n"
        "# Run PGAS\n"
        "model_lev = SVLeverageWrapper()\n"
        "prior_lev = SVLeveragePrior()\n"
        "true_theta = np.array([-1.0, 0.97, 0.15, -0.5])\n"
        "\n"
        "pgas = PGAS(\n"
        "    model=model_lev,\n"
        "    prior=prior_lev,\n"
        "    n_particles=30,\n"
        "    n_iterations=1000,\n"
        "    param_sampler=sv_leverage_param_sampler,\n"
        "    burnin=300,\n"
        "    thin=1,\n"
        "    seed=42,\n"
        ")\n"
        "\n"
        "print('Running PGAS (N=30, 1000 iterations)...')\n"
        "t0 = time.time()\n"
        "pgas_results = pgas.run(endog=y_obs, theta_init=true_theta, verbose=200)\n"
        "elapsed = time.time() - t0\n"
        "print(f'Completed in {elapsed:.1f}s')\n"
        "print(pgas_results.summary())"
    ))

    # --- Cell 7: Posterior of rho ---
    nb.cells.append(new_markdown_cell(
        "## 4. Posterior of $\\rho$ (Leverage Parameter)"
    ))
    nb.cells.append(new_code_cell(
        "samples = pgas_results.posterior_samples\n"
        "rho_samples = samples[:, 3]\n"
        "\n"
        "fig, axes = plt.subplots(1, 2, figsize=(12, 4))\n"
        "\n"
        "# Histogram\n"
        "axes[0].hist(rho_samples, bins=30, density=True, alpha=0.7, color='steelblue')\n"
        "axes[0].axvline(true_params['rho'], color='red', linestyle='--', linewidth=2, label=f'True: {true_params[\"rho\"]}')\n"
        "axes[0].axvline(rho_samples.mean(), color='orange', linewidth=2, label=f'Mean: {rho_samples.mean():.3f}')\n"
        "axes[0].axvline(0, color='k', linestyle=':', linewidth=1)\n"
        "axes[0].set_title('Posterior of $\\\\rho$ (leverage parameter)')\n"
        "axes[0].set_xlabel('$\\\\rho$')\n"
        "axes[0].legend()\n"
        "\n"
        "# Trace plot\n"
        "axes[1].plot(pgas_results.chains[:, 3], linewidth=0.5, color='steelblue')\n"
        "axes[1].axhline(true_params['rho'], color='red', linestyle='--', linewidth=1)\n"
        "axes[1].set_title('Trace Plot of $\\\\rho$')\n"
        "axes[1].set_xlabel('Iteration')\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print(f'Posterior mean rho = {rho_samples.mean():.4f} (true = {true_params[\"rho\"]})')\n"
        "print(f'P(rho < 0) = {(rho_samples < 0).mean():.3f}')"
    ))

    # --- Cell 8: Log-likelihood comparison ---
    nb.cells.append(new_markdown_cell(
        "## 5. Model Comparison: SV Basic vs SV-Leverage\n"
        "\n"
        "We compare the two models using the particle filter log-likelihood "
        "evaluated at the posterior mean parameters."
    ))
    nb.cells.append(new_code_cell(
        "post_mean = pgas_results.posterior_mean()\n"
        "mu_hat, phi_hat, sig_hat, rho_hat = post_mean\n"
        "\n"
        "# SV basic (rho=0) vs SV-L at posterior means\n"
        "ll_basic = bootstrap_pf_sv_leverage(\n"
        "    y_obs, mu=mu_hat, phi=phi_hat, sigma=sig_hat, rho=0.0,\n"
        "    n_particles=2000, seed=99\n"
        ")['log_likelihood']\n"
        "ll_leverage = bootstrap_pf_sv_leverage(\n"
        "    y_obs, mu=mu_hat, phi=phi_hat, sigma=sig_hat, rho=rho_hat,\n"
        "    n_particles=2000, seed=99\n"
        ")['log_likelihood']\n"
        "\n"
        "print(f'Log-likelihood comparison at posterior mean params:')\n"
        "print(f'  SV basic (rho=0): {ll_basic:.2f}')\n"
        "print(f'  SV-L (rho={rho_hat:.3f}): {ll_leverage:.2f}')\n"
        "print(f'  Difference:        {ll_leverage - ll_basic:.2f}')\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(8, 4))\n"
        "models = ['SV Basic', 'SV-Leverage']\n"
        "lls = [ll_basic, ll_leverage]\n"
        "colors = ['steelblue', 'darkorange']\n"
        "ax.barh(models, lls, color=colors)\n"
        "ax.set_xlabel('Log-Likelihood')\n"
        "ax.set_title('Model Comparison via Log-Likelihood')\n"
        "for i, v in enumerate(lls):\n"
        "    ax.text(v + 0.5, i, f'{v:.1f}', va='center')\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    # --- Cell 9: Asymmetric response ---
    nb.cells.append(new_markdown_cell(
        "## 6. Asymmetric Volatility Response\n"
        "\n"
        "The leverage effect implies that negative return shocks increase volatility "
        "more than positive shocks of the same magnitude."
    ))
    nb.cells.append(new_code_cell(
        "# Simulate impulse responses at posterior mean parameters\n"
        "rng_ir = np.random.default_rng(123)\n"
        "n_sims = 5000\n"
        "H_ir = 20\n"
        "\n"
        "h0 = mu_hat  # start at mean\n"
        "shocks = [-2.0, -1.0, 0.0, 1.0, 2.0]\n"
        "responses = {}\n"
        "\n"
        "for shock in shocks:\n"
        "    h_paths = np.zeros((n_sims, H_ir))\n"
        "    for s in range(n_sims):\n"
        "        # First step: correlated shock\n"
        "        eta = rho_hat * shock + np.sqrt(max(1.0 - rho_hat**2, 1e-10)) * rng_ir.standard_normal()\n"
        "        h_paths[s, 0] = mu_hat + phi_hat * (h0 - mu_hat) + sig_hat * eta\n"
        "        for t in range(1, H_ir):\n"
        "            h_paths[s, t] = mu_hat + phi_hat * (h_paths[s, t-1] - mu_hat) + sig_hat * rng_ir.standard_normal()\n"
        "    responses[shock] = h_paths.mean(axis=0)\n"
        "\n"
        "fig, ax = plt.subplots(figsize=(10, 5))\n"
        "colors_ir = ['darkred', 'salmon', 'grey', 'cornflowerblue', 'darkblue']\n"
        "for shock, color in zip(shocks, colors_ir):\n"
        "    label = f'$\\\\varepsilon_t = {shock:+.0f}$'\n"
        "    ax.plot(range(H_ir), np.exp(responses[shock] / 2.0), color=color, linewidth=2, label=label)\n"
        "\n"
        "ax.set_xlabel('Horizon')\n"
        "ax.set_ylabel('Expected Volatility $E[\\\\exp(h_{t+k}/2)]$')\n"
        "ax.set_title(f'Asymmetric Volatility Response ($\\\\rho = {rho_hat:.2f}$)')\n"
        "ax.legend()\n"
        "ax.axhline(np.exp(mu_hat / 2.0), color='k', linestyle=':', alpha=0.5)\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "print('Negative shocks produce larger volatility increases than positive shocks')\n"
        "print(f'Vol after eps=-2: {np.exp(responses[-2.0][0]/2):.4f}')\n"
        "print(f'Vol after eps=+2: {np.exp(responses[2.0][0]/2):.4f}')"
    ))

    # --- Cell 10: Parameter table ---
    nb.cells.append(new_markdown_cell(
        "## 7. Parameter Estimates vs True Values"
    ))
    nb.cells.append(new_code_cell(
        "post_mean = pgas_results.posterior_mean()\n"
        "post_std = pgas_results.posterior_std()\n"
        "ci_low, ci_high = pgas_results.credible_interval(alpha=0.05)\n"
        "param_names = ['mu', 'phi', 'sigma', 'rho']\n"
        "true_vals = [-1.0, 0.97, 0.15, -0.5]\n"
        "\n"
        "summary_df = pd.DataFrame({\n"
        "    'Parameter': param_names,\n"
        "    'True': true_vals,\n"
        "    'Post. Mean': post_mean,\n"
        "    'Post. Std': post_std,\n"
        "    '95% CI Low': ci_low,\n"
        "    '95% CI High': ci_high,\n"
        "    'Covers True': [(ci_low[i] <= true_vals[i] <= ci_high[i]) for i in range(4)],\n"
        "})\n"
        "print(summary_df.to_string(index=False))\n"
        "summary_df"
    ))

    # --- Cell 11: Discussion ---
    nb.cells.append(new_markdown_cell(
        "## 8. Economic Importance of the Leverage Effect\n"
        "\n"
        "The leverage effect has important implications for:\n"
        "\n"
        "1. **Option pricing**: Negative $\\rho$ generates the volatility smile/skew observed in option markets\n"
        "2. **Risk management**: VaR and ES estimates that ignore leverage underestimate left-tail risk\n"
        "3. **Portfolio allocation**: Volatility increases in falling markets amplify drawdowns,\n"
        "   making diversification more critical precisely when markets decline\n"
        "4. **Volatility forecasting**: Models without leverage produce symmetric forecasts that\n"
        "   systematically underpredict volatility following market declines\n"
        "\n"
        "Our PGAS estimation confirms $\\rho < 0$ with high posterior probability,\n"
        "validating the importance of this feature for financial applications.\n"
        "\n"
        "Next: [03_sv_jumps_factor.ipynb](03_sv_jumps_factor.ipynb) — jumps and factor models"
    ))

    return nb


# ============================================================================
# Notebook 3: SV Jumps and Factor SV
# ============================================================================

def build_nb3() -> nbf.NotebookNode:
    """03_sv_jumps_factor.ipynb — SV with jumps and factor SV."""
    nb = new_notebook()
    nb.metadata.kernelspec = {
        "display_name": "Python 3",
        "language": "python",
        "name": "python3",
    }

    # --- Cell 1: Title ---
    nb.cells.append(new_markdown_cell(
        "# SV with Jumps and Factor SV\n"
        "\n"
        "This notebook demonstrates two advanced extensions of the stochastic volatility model:\n"
        "\n"
        "1. **SV with Jumps (SV-J)**: Adds Poisson-driven jumps to capture sudden large moves:\n"
        "   $$y_t = \\exp(h_t/2)\\,\\varepsilon_t + J_t\\,Z_t$$\n"
        "   where $J_t \\sim \\text{Bernoulli}(\\lambda)$ and $Z_t \\sim N(\\mu_J, \\sigma_J^2)$\n"
        "\n"
        "2. **Factor SV**: A multivariate model with a common volatility factor driving\n"
        "   $K$ correlated asset returns:\n"
        "   $$y_{k,t} = \\exp\\bigl((\\beta_k h_t + h_{k,t})/2\\bigr)\\,\\varepsilon_{k,t}$$\n"
        "\n"
        "We filter using the **Auxiliary Particle Filter** (for SV-J) and a simplified\n"
        "**Rao-Blackwellized** approach (for Factor SV)."
    ))

    # --- Cell 2: Imports ---
    nb.cells.append(new_code_cell(
        "import sys, os\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "%matplotlib inline\n"
        "from scipy import stats\n"
        "import time\n"
        "\n"
        "sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..', '..', '..')))\n"
        "\n"
        "from particlefilterbox.models.stochastic_volatility import StochasticVolatility\n"
        "\n"
        "plt.rcParams['figure.figsize'] = (12, 5)\n"
        "plt.rcParams['figure.dpi'] = 100\n"
        "np.random.seed(42)"
    ))

    # --- Cell 3: Generate SV-J data ---
    nb.cells.append(new_markdown_cell(
        "## Part 1: SV with Jumps (SV-J)\n"
        "\n"
        "### 1.1 Synthetic Data Generation\n"
        "\n"
        "We generate data from the SV-J model using `particlefilterbox`."
    ))
    nb.cells.append(new_code_cell(
        "# Generate data with the jumps variant\n"
        "sv_jumps = StochasticVolatility(\n"
        "    variant='jumps',\n"
        "    params={\n"
        "        'mu': -1.0, 'phi': 0.97, 'sigma': 0.15,\n"
        "        'lambda_jump': 0.05,    # ~5% chance of jump each period\n"
        "        'mu_jump': -0.5,        # negative mean jump (crash-like)\n"
        "        'sigma_jump': 1.0,      # jump size std\n"
        "    }\n"
        ")\n"
        "\n"
        "sim_j = sv_jumps.simulate(T=500, seed=42)\n"
        "y_jumps = sim_j['observations'][:, 0]  # (T,)\n"
        "h_true_j = sim_j['states'][:, 0]       # log-vol\n"
        "q_true_j = sim_j['states'][:, 1]       # jump indicator\n"
        "\n"
        "print(f'Generated {len(y_jumps)} observations')\n"
        "print(f'Number of jumps: {int(q_true_j.sum())} ({q_true_j.mean()*100:.1f}%)')\n"
        "print(f'Jump times: {np.where(q_true_j > 0.5)[0][:20]}...')"
    ))

    # --- Cell 4: Exploratory analysis of jump data ---
    nb.cells.append(new_markdown_cell(
        "### 1.2 Exploratory Analysis of Jump Data"
    ))
    nb.cells.append(new_code_cell(
        "fig, axes = plt.subplots(2, 2, figsize=(14, 8))\n"
        "\n"
        "# Returns\n"
        "axes[0, 0].plot(y_jumps, linewidth=0.5, color='steelblue')\n"
        "jump_times = np.where(q_true_j > 0.5)[0]\n"
        "axes[0, 0].scatter(jump_times, y_jumps[jump_times], color='red', s=20, zorder=5, label='Jump times')\n"
        "axes[0, 0].set_title('Returns with Jumps')\n"
        "axes[0, 0].legend()\n"
        "\n"
        "# Histogram\n"
        "axes[0, 1].hist(y_jumps, bins=60, density=True, alpha=0.7, color='steelblue')\n"
        "x_grid = np.linspace(y_jumps.min(), y_jumps.max(), 200)\n"
        "axes[0, 1].plot(x_grid, stats.norm.pdf(x_grid, y_jumps.mean(), y_jumps.std()),\n"
        "               'r-', linewidth=2, label='Normal fit')\n"
        "axes[0, 1].set_title(f'Distribution (kurtosis={stats.kurtosis(y_jumps):.2f})')\n"
        "axes[0, 1].legend()\n"
        "\n"
        "# True log-volatility\n"
        "axes[1, 0].plot(h_true_j, linewidth=0.8, color='darkred')\n"
        "axes[1, 0].set_title('True Log-Volatility $h_t$')\n"
        "\n"
        "# True jump indicators\n"
        "axes[1, 1].stem(range(len(q_true_j)), q_true_j, linefmt='r-', markerfmt='ro', basefmt='k-')\n"
        "axes[1, 1].set_title(f'True Jump Indicators $J_t$ ({int(q_true_j.sum())} jumps)')\n"
        "axes[1, 1].set_ylim(-0.1, 1.5)\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    # --- Cell 5: Auxiliary PF on SV-J ---
    nb.cells.append(new_markdown_cell(
        "### 1.3 Filtering SV-J with Auxiliary Particle Filter\n"
        "\n"
        "The Auxiliary PF uses the predictive likelihood to pre-select particles, "
        "which is beneficial when observations are informative about the state (as with jumps)."
    ))
    nb.cells.append(new_code_cell(
        "def auxiliary_pf_svj(\n"
        "    y: np.ndarray,\n"
        "    params: dict,\n"
        "    n_particles: int = 1000,\n"
        "    seed: int = 42,\n"
        ") -> dict:\n"
        "    \"\"\"Auxiliary PF for SV-J model. Returns filtered h, q, and log-likelihood.\"\"\"\n"
        "    rng = np.random.default_rng(seed)\n"
        "    T = len(y)\n"
        "    mu, phi, sigma = params['mu'], params['phi'], params['sigma']\n"
        "    lam = params['lambda_jump']\n"
        "    mu_j, sigma_j = params['mu_jump'], params['sigma_jump']\n"
        "    \n"
        "    var_stat = sigma**2 / (1.0 - phi**2)\n"
        "    h_particles = rng.normal(mu, np.sqrt(var_stat), size=n_particles)\n"
        "    q_particles = rng.binomial(1, lam, size=n_particles).astype(float)\n"
        "    \n"
        "    filtered_h_mean = np.zeros(T)\n"
        "    filtered_h_std = np.zeros(T)\n"
        "    filtered_q_mean = np.zeros(T)  # P(jump at t)\n"
        "    log_lik = 0.0\n"
        "    \n"
        "    for t in range(T):\n"
        "        # --- APF Stage 1: first-stage weights using predictive mean ---\n"
        "        if t > 0:\n"
        "            # Predictive h (deterministic part)\n"
        "            h_pred = mu + phi * (h_particles - mu)\n"
        "            q_pred_prob = lam * np.ones(n_particles)  # predicted jump probability\n"
        "        else:\n"
        "            h_pred = h_particles\n"
        "            q_pred_prob = q_particles\n"
        "        \n"
        "        # First-stage weight: p(y_t | h_pred, q=0)*(1-lam) + p(y_t | h_pred, q=1)*lam\n"
        "        vol_pred = np.exp(h_pred / 2.0)\n"
        "        var_no = vol_pred**2\n"
        "        var_yes = vol_pred**2 + sigma_j**2\n"
        "        log_p_no = -0.5 * np.log(2 * np.pi * var_no) - 0.5 * y[t]**2 / var_no\n"
        "        log_p_yes = -0.5 * np.log(2 * np.pi * var_yes) - 0.5 * (y[t] - mu_j)**2 / var_yes\n"
        "        max_p = np.maximum(log_p_no, log_p_yes)\n"
        "        first_w = (1 - lam) * np.exp(log_p_no - max_p) + lam * np.exp(log_p_yes - max_p)\n"
        "        first_w_sum = np.sum(first_w)\n"
        "        if first_w_sum < 1e-300:\n"
        "            first_w = np.ones(n_particles) / n_particles\n"
        "        else:\n"
        "            first_w /= first_w_sum\n"
        "        \n"
        "        # Resample based on first-stage weights\n"
        "        idx = rng.choice(n_particles, size=n_particles, p=first_w)\n"
        "        h_particles = h_particles[idx]\n"
        "        \n"
        "        # --- Stage 2: propagate ---\n"
        "        if t > 0:\n"
        "            h_particles = mu + phi * (h_particles - mu) + sigma * rng.standard_normal(n_particles)\n"
        "        q_particles = rng.binomial(1, lam, size=n_particles).astype(float)\n"
        "        \n"
        "        # --- Second-stage weights: p(y|h,q) / first-stage-approx ---\n"
        "        vol = np.exp(h_particles / 2.0)\n"
        "        var_no_2 = vol**2\n"
        "        var_yes_2 = vol**2 + sigma_j**2\n"
        "        log_p_actual = np.where(\n"
        "            q_particles > 0.5,\n"
        "            -0.5 * np.log(2 * np.pi * var_yes_2) - 0.5 * (y[t] - mu_j)**2 / var_yes_2,\n"
        "            -0.5 * np.log(2 * np.pi * var_no_2) - 0.5 * y[t]**2 / var_no_2\n"
        "        )\n"
        "        \n"
        "        # Normalize (simple version: equal adjustment weights)\n"
        "        max_lw = np.max(log_p_actual)\n"
        "        w = np.exp(log_p_actual - max_lw)\n"
        "        sw = np.sum(w)\n"
        "        if sw < 1e-300:\n"
        "            w = np.ones(n_particles) / n_particles\n"
        "            log_lik += -100.0  # penalty\n"
        "        else:\n"
        "            log_lik += max_lw + np.log(sw) - np.log(n_particles)\n"
        "            w /= sw\n"
        "        \n"
        "        filtered_h_mean[t] = np.sum(w * h_particles)\n"
        "        filtered_h_std[t] = np.sqrt(np.sum(w * (h_particles - filtered_h_mean[t])**2))\n"
        "        filtered_q_mean[t] = np.sum(w * q_particles)\n"
        "        \n"
        "        # Resample for next step\n"
        "        idx = rng.choice(n_particles, size=n_particles, p=w)\n"
        "        h_particles = h_particles[idx]\n"
        "        q_particles = q_particles[idx]\n"
        "    \n"
        "    return {\n"
        "        'h_mean': filtered_h_mean,\n"
        "        'h_std': filtered_h_std,\n"
        "        'q_prob': filtered_q_mean,\n"
        "        'log_likelihood': log_lik,\n"
        "    }\n"
        "\n"
        "# Run APF on SV-J data\n"
        "params_j = {\n"
        "    'mu': -1.0, 'phi': 0.97, 'sigma': 0.15,\n"
        "    'lambda_jump': 0.05, 'mu_jump': -0.5, 'sigma_jump': 1.0,\n"
        "}\n"
        "\n"
        "t0 = time.time()\n"
        "apf_result = auxiliary_pf_svj(y_jumps, params_j, n_particles=1000, seed=42)\n"
        "elapsed = time.time() - t0\n"
        "print(f'Auxiliary PF completed in {elapsed:.2f}s')\n"
        "print(f'Log-likelihood: {apf_result[\"log_likelihood\"]:.2f}')"
    ))

    # --- Cell 6: Jump detection plot ---
    nb.cells.append(new_markdown_cell(
        "### 1.4 Jump Detection"
    ))
    nb.cells.append(new_code_cell(
        "fig, axes = plt.subplots(3, 1, figsize=(14, 10), sharex=True)\n"
        "\n"
        "# Returns with detected jumps\n"
        "axes[0].plot(y_jumps, linewidth=0.5, color='steelblue')\n"
        "high_prob = apf_result['q_prob'] > 0.3\n"
        "axes[0].scatter(np.where(high_prob)[0], y_jumps[high_prob],\n"
        "               color='red', s=25, zorder=5, label='Detected (P>0.3)')\n"
        "axes[0].set_title('Returns with Detected Jumps')\n"
        "axes[0].set_ylabel('$y_t$')\n"
        "axes[0].legend()\n"
        "\n"
        "# True vs filtered jump probability\n"
        "axes[1].fill_between(range(len(q_true_j)), q_true_j, alpha=0.3, color='red', label='True $J_t$')\n"
        "axes[1].plot(apf_result['q_prob'], color='darkblue', linewidth=1, label='$P(J_t=1 | y_{1:t})$')\n"
        "axes[1].set_title('Jump Detection: True vs Filtered')\n"
        "axes[1].set_ylabel('Jump probability')\n"
        "axes[1].legend()\n"
        "\n"
        "# Filtered vs true log-volatility\n"
        "axes[2].plot(h_true_j, color='black', linewidth=0.8, alpha=0.6, label='True $h_t$')\n"
        "axes[2].plot(apf_result['h_mean'], color='darkred', linewidth=1.2, label='Filtered $h_t$')\n"
        "h_upper = apf_result['h_mean'] + 1.96 * apf_result['h_std']\n"
        "h_lower = apf_result['h_mean'] - 1.96 * apf_result['h_std']\n"
        "axes[2].fill_between(range(len(h_true_j)), h_lower, h_upper, alpha=0.2, color='salmon')\n"
        "axes[2].set_title('Filtered Log-Volatility')\n"
        "axes[2].set_ylabel('$h_t$')\n"
        "axes[2].set_xlabel('Time')\n"
        "axes[2].legend()\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()\n"
        "\n"
        "# Detection metrics\n"
        "threshold = 0.3\n"
        "detected = apf_result['q_prob'] > threshold\n"
        "true_jumps = q_true_j > 0.5\n"
        "tp = np.sum(detected & true_jumps)\n"
        "fp = np.sum(detected & ~true_jumps)\n"
        "fn = np.sum(~detected & true_jumps)\n"
        "precision = tp / max(tp + fp, 1)\n"
        "recall = tp / max(tp + fn, 1)\n"
        "print(f'\\nJump detection (threshold={threshold}):')\n"
        "print(f'  True positives: {tp}, False positives: {fp}, False negatives: {fn}')\n"
        "print(f'  Precision: {precision:.3f}, Recall: {recall:.3f}')"
    ))

    # --- Cell 7: Factor SV ---
    nb.cells.append(new_markdown_cell(
        "## Part 2: Factor SV for Multiple Series\n"
        "\n"
        "### 2.1 Synthetic Multivariate Data\n"
        "\n"
        "The Factor SV model assumes $K$ observed series share a common volatility factor $h_t$ "
        "plus idiosyncratic volatility $h_{k,t}$:\n"
        "\n"
        "$$y_{k,t} = \\exp\\bigl((\\beta_k h_t + h_{k,t})/2\\bigr)\\,\\varepsilon_{k,t}$$"
    ))
    nb.cells.append(new_code_cell(
        "# Generate factor SV data with 3 series\n"
        "sv_factor = StochasticVolatility(\n"
        "    variant='factor',\n"
        "    k_factor_series=3,\n"
        "    params={\n"
        "        'mu': -1.0, 'phi': 0.97, 'sigma': 0.15,\n"
        "        'phi_0': 0.95, 'sigma_0': 0.2, 'beta_0': 1.0,\n"
        "        'phi_1': 0.90, 'sigma_1': 0.25, 'beta_1': 0.8,\n"
        "        'phi_2': 0.93, 'sigma_2': 0.18, 'beta_2': 1.2,\n"
        "    }\n"
        ")\n"
        "\n"
        "sim_f = sv_factor.simulate(T=500, seed=123)\n"
        "y_factor = sim_f['observations']  # (T, 3)\n"
        "states_f = sim_f['states']         # (T, 4): h_common, h_0, h_1, h_2\n"
        "h_common_true = states_f[:, 0]\n"
        "\n"
        "print(f'Factor SV: {y_factor.shape[1]} series, {y_factor.shape[0]} observations')\n"
        "print(f'States shape: {states_f.shape} (common + {sv_factor.k_factor_series} idiosyncratic)')"
    ))

    # --- Cell 8: Multivariate data exploration ---
    nb.cells.append(new_code_cell(
        "fig, axes = plt.subplots(2, 2, figsize=(14, 8))\n"
        "series_names = ['Series 0 (beta=1.0)', 'Series 1 (beta=0.8)', 'Series 2 (beta=1.2)']\n"
        "colors = ['steelblue', 'darkorange', 'forestgreen']\n"
        "\n"
        "# Individual series\n"
        "for k in range(3):\n"
        "    axes[0, 0].plot(y_factor[:, k], linewidth=0.4, color=colors[k], alpha=0.7, label=series_names[k])\n"
        "axes[0, 0].set_title('Factor SV: Three Correlated Series')\n"
        "axes[0, 0].legend(fontsize=8)\n"
        "\n"
        "# Squared returns show common factor\n"
        "for k in range(3):\n"
        "    axes[0, 1].plot(y_factor[:, k]**2, linewidth=0.4, color=colors[k], alpha=0.5)\n"
        "axes[0, 1].set_title('Squared Returns (common volatility pattern)')\n"
        "\n"
        "# True common factor\n"
        "axes[1, 0].plot(h_common_true, color='darkred', linewidth=1)\n"
        "axes[1, 0].set_title('True Common Volatility Factor $h_t$')\n"
        "axes[1, 0].set_xlabel('Time')\n"
        "\n"
        "# Correlation matrix of returns\n"
        "corr_mat = np.corrcoef(y_factor.T)\n"
        "im = axes[1, 1].imshow(corr_mat, cmap='RdBu_r', vmin=-1, vmax=1)\n"
        "axes[1, 1].set_title('Return Correlations')\n"
        "axes[1, 1].set_xticks([0, 1, 2])\n"
        "axes[1, 1].set_yticks([0, 1, 2])\n"
        "for i in range(3):\n"
        "    for j in range(3):\n"
        "        axes[1, 1].text(j, i, f'{corr_mat[i,j]:.2f}', ha='center', va='center')\n"
        "plt.colorbar(im, ax=axes[1, 1])\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    # --- Cell 9: RBPF for factor SV ---
    nb.cells.append(new_markdown_cell(
        "### 2.2 Filtering the Common Factor with RBPF\n"
        "\n"
        "We use a particle filter that targets the common factor $h_t$, "
        "marginalizing over the idiosyncratic components where possible. "
        "For simplicity, we implement a bootstrap PF on the full state."
    ))
    nb.cells.append(new_code_cell(
        "def pf_factor_sv(\n"
        "    y: np.ndarray,\n"
        "    params: dict,\n"
        "    K: int = 3,\n"
        "    n_particles: int = 500,\n"
        "    seed: int = 42,\n"
        ") -> dict:\n"
        "    \"\"\"Particle filter for Factor SV model.\n"
        "    \n"
        "    State: (h_common, h_0, h_1, ..., h_{K-1})\n"
        "    Uses Rao-Blackwellization by marginalizing idiosyncratic components\n"
        "    conditional on the common factor.\n"
        "    \"\"\"\n"
        "    rng = np.random.default_rng(seed)\n"
        "    T = y.shape[0]\n"
        "    mu, phi, sigma = params['mu'], params['phi'], params['sigma']\n"
        "    \n"
        "    # Initialize common factor particles\n"
        "    var_stat = sigma**2 / (1.0 - phi**2)\n"
        "    h_common = rng.normal(mu, np.sqrt(var_stat), size=n_particles)\n"
        "    \n"
        "    # Initialize idiosyncratic states\n"
        "    h_idio = np.zeros((n_particles, K))\n"
        "    for k in range(K):\n"
        "        phi_k = params[f'phi_{k}']\n"
        "        sigma_k = params[f'sigma_{k}']\n"
        "        var_k = sigma_k**2 / (1.0 - phi_k**2)\n"
        "        h_idio[:, k] = rng.normal(0, np.sqrt(var_k), size=n_particles)\n"
        "    \n"
        "    filtered_h_common = np.zeros(T)\n"
        "    filtered_h_common_std = np.zeros(T)\n"
        "    log_lik = 0.0\n"
        "    \n"
        "    for t in range(T):\n"
        "        # Compute log-weights: sum of log p(y_{k,t} | h_common, h_k)\n"
        "        log_w = np.zeros(n_particles)\n"
        "        for k in range(K):\n"
        "            beta_k = params[f'beta_{k}']\n"
        "            vol_k = np.exp((beta_k * h_common + h_idio[:, k]) / 2.0)\n"
        "            log_w += -0.5 * np.log(2 * np.pi) - np.log(vol_k) - 0.5 * (y[t, k] / vol_k)**2\n"
        "        \n"
        "        max_lw = np.max(log_w)\n"
        "        w = np.exp(log_w - max_lw)\n"
        "        sw = np.sum(w)\n"
        "        if sw < 1e-300:\n"
        "            w = np.ones(n_particles) / n_particles\n"
        "        else:\n"
        "            log_lik += max_lw + np.log(sw) - np.log(n_particles)\n"
        "            w /= sw\n"
        "        \n"
        "        filtered_h_common[t] = np.sum(w * h_common)\n"
        "        filtered_h_common_std[t] = np.sqrt(np.sum(w * (h_common - filtered_h_common[t])**2))\n"
        "        \n"
        "        # Resample\n"
        "        idx = rng.choice(n_particles, size=n_particles, p=w)\n"
        "        h_common = h_common[idx]\n"
        "        h_idio = h_idio[idx]\n"
        "        \n"
        "        # Propagate\n"
        "        h_common = mu + phi * (h_common - mu) + sigma * rng.standard_normal(n_particles)\n"
        "        for k in range(K):\n"
        "            phi_k = params[f'phi_{k}']\n"
        "            sigma_k = params[f'sigma_{k}']\n"
        "            h_idio[:, k] = phi_k * h_idio[:, k] + sigma_k * rng.standard_normal(n_particles)\n"
        "    \n"
        "    return {\n"
        "        'h_common_mean': filtered_h_common,\n"
        "        'h_common_std': filtered_h_common_std,\n"
        "        'log_likelihood': log_lik,\n"
        "    }\n"
        "\n"
        "# Run\n"
        "params_f = {\n"
        "    'mu': -1.0, 'phi': 0.97, 'sigma': 0.15,\n"
        "    'phi_0': 0.95, 'sigma_0': 0.2, 'beta_0': 1.0,\n"
        "    'phi_1': 0.90, 'sigma_1': 0.25, 'beta_1': 0.8,\n"
        "    'phi_2': 0.93, 'sigma_2': 0.18, 'beta_2': 1.2,\n"
        "}\n"
        "\n"
        "t0 = time.time()\n"
        "rbpf_result = pf_factor_sv(y_factor, params_f, K=3, n_particles=500, seed=42)\n"
        "elapsed = time.time() - t0\n"
        "print(f'Factor SV PF completed in {elapsed:.2f}s')\n"
        "print(f'Log-likelihood: {rbpf_result[\"log_likelihood\"]:.2f}')\n"
        "\n"
        "# RMSE of common factor\n"
        "rmse = np.sqrt(np.mean((rbpf_result['h_common_mean'] - h_common_true)**2))\n"
        "print(f'RMSE of common factor h_t: {rmse:.4f}')"
    ))

    # --- Cell 10: Factor SV results plot ---
    nb.cells.append(new_code_cell(
        "fig, axes = plt.subplots(2, 1, figsize=(14, 7), sharex=True)\n"
        "\n"
        "# Common factor\n"
        "axes[0].plot(h_common_true, color='black', linewidth=0.8, alpha=0.6, label='True $h_t$')\n"
        "axes[0].plot(rbpf_result['h_common_mean'], color='darkred', linewidth=1.2, label='Filtered $h_t$')\n"
        "h_up = rbpf_result['h_common_mean'] + 1.96 * rbpf_result['h_common_std']\n"
        "h_lo = rbpf_result['h_common_mean'] - 1.96 * rbpf_result['h_common_std']\n"
        "axes[0].fill_between(range(len(h_common_true)), h_lo, h_up, alpha=0.2, color='salmon')\n"
        "axes[0].set_title('Factor SV: Filtered Common Factor')\n"
        "axes[0].set_ylabel('$h_t$')\n"
        "axes[0].legend()\n"
        "\n"
        "# Implied common volatility vs observed\n"
        "vol_common = np.exp(rbpf_result['h_common_mean'] / 2.0)\n"
        "axes[1].plot(vol_common, color='darkred', linewidth=1.5, label='Common vol $\\\\exp(h_t/2)$')\n"
        "for k, (name, color) in enumerate(zip(series_names, colors)):\n"
        "    axes[1].plot(np.abs(y_factor[:, k]), linewidth=0.3, color=color, alpha=0.4)\n"
        "axes[1].set_title('Common Volatility Factor vs Absolute Returns')\n"
        "axes[1].set_ylabel('Volatility')\n"
        "axes[1].set_xlabel('Time')\n"
        "axes[1].legend()\n"
        "\n"
        "plt.tight_layout()\n"
        "plt.show()"
    ))

    # --- Cell 11: Comparative table ---
    nb.cells.append(new_markdown_cell(
        "## 3. Model Comparison: SV vs SV-L vs SV-J"
    ))
    nb.cells.append(new_code_cell(
        "# Load simulated_sv data for basic SV comparison\n"
        "data_path_sv = os.path.join('..', 'data', 'simulated_sv.csv')\n"
        "df_sv = pd.read_csv(data_path_sv)\n"
        "y_basic = df_sv['y_obs'].values[:500]\n"
        "h_true_basic = df_sv['h_true'].values[:500]\n"
        "\n"
        "# Basic SV filter on basic data\n"
        "def bootstrap_pf_basic(y, mu, phi, sigma, n_particles=1000, seed=42):\n"
        "    rng = np.random.default_rng(seed)\n"
        "    T = len(y)\n"
        "    var_stat = sigma**2 / (1.0 - phi**2)\n"
        "    particles = rng.normal(mu, np.sqrt(var_stat), size=n_particles)\n"
        "    log_lik = 0.0\n"
        "    rmse_sum = 0.0\n"
        "    for t in range(T):\n"
        "        vol = np.exp(particles / 2.0)\n"
        "        log_w = -0.5 * np.log(2 * np.pi) - np.log(vol) - 0.5 * (y[t] / vol)**2\n"
        "        max_lw = np.max(log_w)\n"
        "        w = np.exp(log_w - max_lw)\n"
        "        sw = np.sum(w)\n"
        "        if sw < 1e-300:\n"
        "            return {'log_likelihood': -np.inf}\n"
        "        log_lik += max_lw + np.log(sw) - np.log(n_particles)\n"
        "        w /= sw\n"
        "        idx = rng.choice(n_particles, size=n_particles, p=w)\n"
        "        particles = particles[idx]\n"
        "        particles = mu + phi * (particles - mu) + sigma * rng.standard_normal(n_particles)\n"
        "    return {'log_likelihood': log_lik}\n"
        "\n"
        "ll_sv = bootstrap_pf_basic(y_basic, -1.0, 0.97, 0.15)['log_likelihood']\n"
        "\n"
        "# Compare models\n"
        "comparison = pd.DataFrame({\n"
        "    'Model': ['SV Basic', 'SV-Leverage', 'SV-Jumps', 'Factor SV'],\n"
        "    'State Dim': [1, 1, 2, '1+K'],\n"
        "    'Parameters': [3, 4, 6, '3+3K'],\n"
        "    'Key Feature': [\n"
        "        'Baseline',\n"
        "        'Corr(eps, eta) = rho',\n"
        "        'Poisson jumps in returns',\n"
        "        'Common + idiosyncratic vol',\n"
        "    ],\n"
        "    'Best For': [\n"
        "        'Single series, no asymmetry',\n"
        "        'Equity indices, options',\n"
        "        'Crash-prone assets, FX',\n"
        "        'Multi-asset portfolios',\n"
        "    ],\n"
        "})\n"
        "print(comparison.to_string(index=False))\n"
        "comparison"
    ))

    # --- Cell 12: Conclusion ---
    nb.cells.append(new_markdown_cell(
        "## 4. Conclusion: Choosing the Right SV Model\n"
        "\n"
        "| Data Characteristic | Recommended Model |\n"
        "|---|---|\n"
        "| Moderate volatility clustering | SV Basic |\n"
        "| Asymmetric volatility response to positive/negative shocks | SV-Leverage |\n"
        "| Fat tails with occasional extreme moves | SV-Jumps |\n"
        "| Multiple correlated assets | Factor SV |\n"
        "\n"
        "**Key takeaways:**\n"
        "\n"
        "- **SV-J** can identify jump times with reasonable precision using the Auxiliary PF\n"
        "- **Factor SV** extracts a common volatility driver from multiple series,\n"
        "  enabling portfolio-level risk assessment\n"
        "- The **Auxiliary PF** provides better particle allocation for SV-J than the Bootstrap PF\n"
        "- All models are estimated within the `particlefilterbox` framework\n"
        "\n"
        "For production use, combine model selection criteria (e.g., marginal likelihood via SMC$^2$)\n"
        "with economic intuition about the data-generating process."
    ))

    return nb


# ============================================================================
# Execute notebook
# ============================================================================

def execute_notebook(nb: nbf.NotebookNode, cwd: str) -> nbf.NotebookNode:
    """Execute a notebook and return it with outputs."""
    import nbformat
    from nbconvert.preprocessors import ExecutePreprocessor

    ep = ExecutePreprocessor(timeout=600, kernel_name="python3")
    ep.preprocess(nb, {"metadata": {"path": cwd}})
    return nb


# ============================================================================
# Main
# ============================================================================

def main() -> None:
    out_dir = os.path.dirname(os.path.abspath(__file__))
    cwd = out_dir  # notebooks run from their directory

    notebooks = [
        ("01_sv_basic.ipynb", build_nb1),
        ("02_sv_leverage.ipynb", build_nb2),
        ("03_sv_jumps_factor.ipynb", build_nb3),
    ]

    for fname, builder in notebooks:
        path = os.path.join(out_dir, fname)
        print(f"\n{'='*60}")
        print(f"Building {fname}...")
        nb = builder()
        print(f"  {len(nb.cells)} cells")

        print(f"  Executing...")
        try:
            nb = execute_notebook(nb, cwd)
            print(f"  ✓ Execution successful")
        except Exception as e:
            print(f"  ✗ Execution failed: {e}")
            # Save anyway so we can debug
            raise

        nbf.write(nb, open(path, "w"))
        print(f"  Saved to {path}")

    print(f"\n{'='*60}")
    print("All notebooks built and executed successfully!")


if __name__ == "__main__":
    main()
